apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-application-operator
    control-plane: controller-manager
  name: aloys-webhook-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-application-operator
  name: aloys-webhook-controller-manager
  namespace: aloys-webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aloys-webhook-cpu-oversell-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-application-operator
  name: aloys-webhook-cpu-oversell-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aloys-webhook-cpu-oversell-role
subjects:
- kind: ServiceAccount
  name: aloys-webhook-controller-manager
  namespace: aloys-webhook-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-application-operator
    control-plane: controller-manager
  name: aloys-webhook-metrics-service
  namespace: aloys-webhook-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-webhook-example
  name: aloys-webhook-webhook-service
  namespace: aloys-webhook-system
spec:
  ports:
  - port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-webhook-example
    control-plane: controller-manager
  name: aloys-webhook-controller-manager
  namespace: aloys-webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-bind-address=8443
        - --tls-cert-file=/certs/tls.crt
        - --tls-private-key-file=/certs/tls.key
        - --webhook-bind-address=9443
        - --log-level=debug
        command:
        - /manager
        image: docker.io/library/aloys-webhook:v0.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics-server
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8443
          name: metrics-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: metrics-server
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: aloys-webhook-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: aloys-webhook-example
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: aloys-webhook-example
  name: aloys-webhook-serving-cert
  namespace: aloys-webhook-system
spec:
  dnsNames:
  - aloys-webhook-webhook-service.aloys-webhook-system.svc
  - aloys-webhook-webhook-service.aloys-webhook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: aloys-webhook-serving-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-webhook-example
  name: aloys-webhook-serving-issuer
  namespace: aloys-webhook-system
spec:
  selfSigned: {}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aloys-application-operator
    control-plane: controller-manager
  name: aloys-webhook-metrics-monitor
  namespace: aloys-webhook-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: aloys-webhook-system/aloys-webhook-serving-cert
  name: aloys-webhook-cpu-oversell
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: aloys-webhook-webhook-service
      namespace: aloys-webhook-system
      path: /mutating-cpu-oversell
      port: 9443
  failurePolicy: Fail
  name: mutating-cpu-oversell.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
    - nodes/status
  sideEffects: None
