---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: node-oversold
webhooks:
- admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutating-node-oversold
  failurePolicy: Fail
  name: mutating-node-oversold.kb.io
  #  权限，就是webhook需要监听资源变更才能进行逻辑，在执行的时候需要相关资源的权限
  sideEffects: None
  rules:
    - operations: [ "UPDATE" ]
      apiGroups: [ "" ]
      apiVersions: [ "v1" ]
      resources: [ "nodes/status" ]

#---
#apiVersion: admissionregistration.k8s.io/v1
#kind: ValidatingWebhookConfiguration
#metadata:
#  name: update_node_oversold_patch
#webhooks:
#- admissionReviewVersions:
#  - v1
#  - v1beta1
#  clientConfig:
#    service:
#      name: webhook-service
#      namespace: system
#      path: /validating-pod-container-limit
#  failurePolicy: Fail
#  name: validating-pod-container-limit.kb.io
#  sideEffects: None
#  rules:
#    - operations: ["CREATE", "UPDATE"]
#      apiGroups: [""]
#      apiVersions: ["v1"]
#      resources: ["pods"]
#  rules:
#  - apiGroups:
#    - apps.aloys.cn
#    apiVersions:
#    - v1
#    operations:
#    - CREATE
#    - UPDATE
#    resources:
#    - applications
  #- admissionReviewVersions:
  #  - v1
  #  - v1beta1
  #  clientConfig:
  #    service:
  #      name: template-manager-service
  #      namespace: system
  #      path: /mutate-apps-aloys-cn-v1-application
  #  failurePolicy: Fail
  #  name: webhook-template-template.kb.io
  ##  权限，就是webhook需要监听资源变更才能进行逻辑，在执行的时候需要相关资源的权限
  #  sideEffects: None
  #  rules:
  #    - operations: [ "UPDATE" ]
  #      apiGroups: [ "" ]
  #      apiVersions: [ "v1" ]
  #      resources: [ "nodes/status" ]
  #  - apiGroups:
  #    - apps.aloys.cn
  #    apiVersions:
  #    - v1
  #    operations:
  #    - CREATE
  #    - UPDATE
  #    resources:
  #    - applications
  #  根据命名空间标签进行匹配
  #    namespaceSelector:
  #      matchLabels:
  #        node-oversold-samples-system: enabled
  #根据对象标签进行匹配
#  objectSelector:
#    matchLabels:
#      node-oversold-samples-system: enabled