---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-pod-dns
webhooks:
- admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutating-pod-dns
#      不是默认的端口要显示指定
      port: 9443
#       failurePolicy 设置为 Fail，这意味着如果 webhook 无法被调用（例如服务不可用），API 请求将会失败
  failurePolicy: Fail
#  将 failurePolicy 改为 Ignore。这样，当 webhook 无法被调用时，API 服务器会忽略 webhook 的结果，并继续处理 API 请求
#  failurePolicy: Ignore
  name: mutating-pod-dns.kb.io
  sideEffects: None
  rules:
#    rules字段用于定义触发webhook的具体条件
    - operations: ["CREATE", "UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1","v1beta1"]
      resources: ["pods"]
  #  根据命名空间标签进行匹配，这个字段用于根据命名空间的标签来选择哪些命名空间中的资源会被这个 webhook 处理。
  #    namespaceSelector:
  #      matchLabels:
  #        cpu-oversell-samples-system: enabled
  #排除特定标签的namespace
  namespaceSelector:
    matchExpressions:
    - key: exclude-webhook-podDns
      operator: DoesNotExist
  #根据对象标签进行匹配，对象选择器则是基于资源对象本身的标签来决定是否对特定资源应用 webhook。
  #  objectSelector:
  #    matchLabels:
  #      cpu-oversell-samples-system: enabled