service:
  webhook_bind_address: 9443   #服务端口
  metrics_bind_address: 8443  #探活端口
  enable_pprof: false   #是否启用 pprof 性能分析
  tls_cert_file: ./tls/certs/tls.crt  #证书文件路径
  tls_private_key_file: ./tls/certs/tls.key  #证书文件路径

logger:
  log_encoding: console   #日志输出格式  console or json 如果选择终端，可以不输出log_output_paths 和log_error_output_paths
  log_level: debug  #日志级别 (debug, info, warn, error, dpanic, panic, fatal)
  log_output_paths:
    - logs/application_access.log
  log_error_output_paths:
    - logs/application_error.log
  max_size: 1    # 单位 MB，最大文件大小
  max_backups: 30  # 保留的最大备份文件数量
  max_age: 7       # 保留的最大天数

application:
  sidecar_image: my-sidecar-image:latest