bases:
  - ../default

patches:
  - patch: |
      - op: "remove"
        path: "/spec/dnsNames"
    target:
      kind: Certificate
  - patch: |
      - op: "add"
        path: "/spec/ipAddresses"
        value: ["172.20.10.3"]
    target:
      kind: Certificate
  - patch: |
      #这里也要注意，如果有多个需要修改的，就添加多个
      #现在这些变成单独的名称了，就不需要学多个了
      - op: "add"
        path: "/webhooks/0/clientConfig/url"
        value: "https://172.20.10.3:9443/mutate-apps-aloys-cn-v1-application"
    target:
      kind: MutatingWebhookConfiguration
  - patch: |
      #这里也要注意，如果有多个需要修改的，就添加多个
      #现在这些变成单独的名称了，就不需要学多个了
      - op: "add"
        path: "/webhooks/0/clientConfig/url"
        value: "https://172.20.10.3:9443/validate-apps-aloys-cn-v1-application"
    target:
      kind: ValidatingWebhookConfiguration
  - patch: |
      #这里也要注意，如果有多个需要修改的，就添加多个
      #现在这些变成单独的名称了，就不需要学多个了
      - op: "remove"
        path: "/webhooks/0/clientConfig/service"
    target:
      kind: MutatingWebhookConfiguration
  - patch: |
      #这里也要注意，如果有多个需要修改的，就添加多个
      #现在这些变成单独的名称了，就不需要学多个了
      - op: "remove"
        path: "/webhooks/0/clientConfig/service"
    target:
      kind: ValidatingWebhookConfiguration
